bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              '%kernel.cache_dir%/hateoas'
    serializer:
        json: hateoas.serializer.json_hal
    twig_extension:
        enabled: true
babdev_pagerfanta:
    # The default Pagerfanta view to use in your application
    default_view: default

    exceptions_strategy:
        # The exception strategy if requesting a page outside the available pages in a paginated list; valid options are "custom" or "to_http_not_found"
        out_of_range_page: to_http_not_found

        # The exception strategy if the current page is not an allowed value in a paginated list; valid options are "custom" or "to_http_not_found"
        not_valid_current_page: to_http_not_found